server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  redis:
    host: localhost
    database: 0 # Redis 数据库索引
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数量(负数表示没有限制)
        max-wait: -1ms # 连接池最大阻塞等待时间(使用负数表示没有限制)
        max-idle: 8 # 连接池最大空闲连接
        min-idle: 0 # 连接池最小空闲连接
    timeout: 3000ms # 连接池超时时间

  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es 的连接地址和端口号
      cluster-name: elasticsearch # 集群的名字

    mongodb:
      uri: mongodb://mall:123456@127.0.0.1:27017/mall-port
  rabbitmq:
    host: localhost
    port: 5672
    username: mall
    password: mall
    virtual-host: /mall # rabbitmq 的虚拟 host
    publisher-confirms: true # 如果对异步消息需要回调必须设置为 true
  main:
    allow-circular-references: true

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

redis:
  database: mall
  key:
    prefix:
      authCode: "portal:authCode"
    expire:
      authCode: 120
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
    member: 'ums:member'
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
  expire:
    authCode: 90 # 验证码超时超时时间
    common: 86400 # 24 小时

# 自定义 jwt key
jwt:
  tokenHeader: "Authorization" # JWT 存储的请求头
  secret: "AutMaple" # JWT 加密解密使用的密钥
  expiration: "604800" # JWT过期时间
  tokenHead: "Bearer" # JWT 负载中拿到开头

springdoc:
  packages-to-scan: com.autmaple.mall.tiny.controller